config/routes.rb
LoremIpsum::Application.routes.draw do
  resources :statuses, except: [:show]

  root 'welcome#index'

  

end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_path, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to statuses_path, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:nombre, :contenido)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lorem Ipsum</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<nav>
		<div class="nav-wrapper">
		<a href="#!" class="brand-logo">Logo</a>
		<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
			<ul class="right hide-on-med-and-down">
				<%= link_to "Inicio", root_path %>
				<%= link_to "Estatus", statuses_path %>
			</ul>
			<ul class="side-nav" id="mobile-demo">
				<%= link_to "Inicio", root_path %>
				<%= link_to "Estatus", statuses_path %>
			</ul>
		</div>
	</nav>
</header>
<div id="notice"><%= notice %></div>
<div class="content">
	<div class="container">
		<%= yield %>
	</div>
</div>
<script type="text/javascript">
	$(".button-collapse").sideNav();
</script>
</body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s8">
      <%= f.label :nombre, for:"nombre" %><br>
      <%= f.text_field :nombre, id:"nombre", class:"validate", required:"true" %>
    </div>
    <div class="input-field col s8">
      <%= f.label :contenido, for:"contenido" %><br>
      <%= f.text_area :contenido, id:"contenido", class:"materialize-textarea", required:"true" %>
    </div>
    <div class="actions col s12">
      <%= button_tag(type: 'submit', class: "btn") do %>
       Ok<i class="material-icons right">►</i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editar Estado</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Estados</h1>
<div class="statuses row">
  <% @statuses.each do |status| %>
    <div class="status z-depth-1 col s7">
      <div class="information col s12">
        <div class="name left">
          <%= link_to status.nombre, status %>
        </div>
        <div class="options right">
          <%= link_to 'Edit', edit_status_path(status) %>
          <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <div class="body col s12">
        <%= status.contenido %>
      </div>
      <div class="timestamp col s12">
        <strong><%= "Hace "+time_ago_in_words(status.created_at, :only => [:days, :hours, :minutes]) %></strong>
      </div>
    </div>
  <% end %>
</div>
<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @status.nombre %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @status.contenido %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>